theme: jekyll-theme-time-machine
# Name of your site (displayed in the header)
title: About Timo Rößner

# Short bio or description (displayed in the header)
description: Seasoned engineering leader and software developer
